version: "3.8"
services:
    nestjs:
        build:
            dockerfile: Dockerfile
            context: ./app
            target: ${NODE_ENV}
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on: 
            - postgres
        env_file:
            - .env
        environment:
            - NODE_ENV:${NODE_ENV}
        volumes:
            - ./app:/usr/src/app
            - /usr/src/app/node_modules
        entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - ${DATABASE_PORT}:${DATABASE_PORT}
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_DB: ${DATABASE_NAME}
            PG_DATA: /var/lib/postgresql/data
        volumes:
            - ./pgdata:/var/lib/postgresql/data