version: "3.8"
services:
    nestjs:
        build:
            dockerfile: Dockerfile
            context: ./app
            target: ${NODE_ENV}
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on: 
            - mongodb
        env_file:
            - .env
        environment:
            - NODE_ENV:${NODE_ENV}
        volumes:
            - ./app:/usr/src/app
            - /usr/src/app/node_modules
        entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    mongodb:
        image: mongo:latest
        restart: always
        ports:
            - ${DATABASE_PORT}:${DATABASE_PORT}
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME} 
            MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MONGO_INITDB_DATABASE: ${DATABASE_NAME}
        volumes:
            - ./mgdata:/data